spring:
  cloud:
    gateway:
      routes:
        - id: user-management-service
          uri: http://localhost:8081/
          predicates:
            - Path=/user/**, /user
        - id: order-service
          uri: http://localhost:8082/
          predicates:
            - Path=/order/**
management:
  endpoints:
    web:
      exposure:
        include: gateway