spring:
  cloud:
    gateway:
      routes:
        - id: user-management-service
          uri: http://localhost:8081
          predicates:
            - Path=/user/**, /user
        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/order/**
management:
  endpoints:
    web:
      exposure:
        include: gateway
  endpoint:
    gateway:
      enabled: true
security:
  auth:
    url: http://ms-auth:8081
    introspect-api: /api/v1/auth/introspect


ms:
  user-mng:
    root: http://ms-user:8082
  auth:
    root: http://ms-auth:8081
  order:
    root: http://ms-order:8083