spring:
  cloud:
    gateway:
      routes:
        - id: userManagementModule
          uri: http://localhost:8081/
          predicates:
            - Path=/user/**
        - id: orderModule
          uri: http://localhost:8082/
          predicates:
            - Path=/order/**
management:
  endpoints:
    web:
      exposure:
        include: gateway